// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5iO7twrmNfA-5Wy5t8QOqh9Bcsib920s',
    appId: '1:485154178475:android:5606267d9aaa52ea7c3eee',
    messagingSenderId: '485154178475',
    projectId: 'flutter-tesk-task-map',
    storageBucket: 'flutter-tesk-task-map.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaYQ3H2YxBnwvnDRjrcDPpb9CWF4FbO14',
    appId: '1:485154178475:ios:53840890511077ce7c3eee',
    messagingSenderId: '485154178475',
    projectId: 'flutter-tesk-task-map',
    storageBucket: 'flutter-tesk-task-map.appspot.com',
    androidClientId: '485154178475-1ubtundb2dqgrermthc1hdseme8vbgju.apps.googleusercontent.com',
    iosClientId: '485154178475-9jr62q8jrq7el692jhb6no8tnv9sn7c5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestTaskMap',
  );
}
